name: CI/CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: read
  actions: read
  id-token: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2 
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          aws-region: us-west-2

      - name: Log in to Amazon ECR 
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2 

      - name: Build Docker image
        run: docker build -t liatrio-iturgut .

      - name: Tag Docker image for Docker Hub and ECR
        run: |
          docker tag liatrio-iturgut:latest 2003ilaydaturgut3155/liatrio-iturgut:latest
          docker tag liatrio-iturgut:latest ${{ secrets.ECR_REGISTRY }}:latest

      - name: Push Docker image to Docker Hub
        run: docker push 2003ilaydaturgut3155/liatrio-iturgut:latest

      - name: Push Docker image to ECR
        run: docker push ${{ secrets.ECR_REGISTRY }}:latest

      - name: Run Docker container
        run: docker run -d -p 80:80 --name liatrio-dockerapp 2003ilaydaturgut3155/liatrio-iturgut:latest

      # third party action
      - name: Use Liatrio Action for Endpoint Tests
        uses: liatrio/github-actions/apprentice-action@v1.0.0 #changed reference from master to v1.0.0

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      #- name: Build and push Docker image 
        #run: | 
          #docker build -t ${{ secrets.ECR_REGISTRY }}:latest -f Dockerfile . 
          #docker push ${{ secrets.ECR_REGISTRY }}:latest 

      - name: Update AWS App Runner service
        run: |
          aws apprunner update-service \
            --service-arn arn:aws:apprunner:us-west-2:296062563852:service/liatrio-service/80834f31f0454317a5552b72a4790101 \
            --source-configuration ImageRepositoryType=ECR \
            --image-repository ImageIdentifier=${{ secrets.ECR_REGISTRY }}:latest,ImageConfiguration={Port=80}